version: '3.7'
services:
  permissions-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env-tests
    ports:
      - 8081:8081
    depends_on:
      - mongo
      - keycloak
    networks:
      private-network:
        ipv4_address: 172.21.0.11
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      private-network:
        ipv4_address: 172.21.0.13
  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    environment:
      DB_VENDOR: ${DB_VENDOR}
      DB_ADDR: ${DB_ADDR}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    volumes:
      - "./ipc-test-data/keycloak/realms:/opt/jboss/keycloak/imports"
      - "./ipc-plugins/keycloak:/opt/jboss/keycloak/standalone/deployments"
    command:
      - '-b 0.0.0.0 -Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.migration.strategy=IGNORE_EXISTING'
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      private-network:
        ipv4_address: 172.21.0.12
  mongo:
    image : mongo:4.4
    hostname: mongo
    restart: on-failure
    environment:
      PUID: 1000
      PGID: 1000
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_REPLICA_SET_NAME: rs0
    volumes:
      - "./ipc-test-data/mdbdata:/data/db"
      - "./keyfile:/opt/keyfile/keyfile"
    ports:
      - 27017:27017
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 30s
    command: "--bind_ip_all --keyFile /opt/keyfile/keyfile --replSet rs0"
    networks:
      private-network:
        ipv4_address: 172.21.0.10
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5
    networks:
      private-network:
        ipv4_address: 172.21.0.24
networks:
  private-network:
    ipam:
      config:
        - subnet: 172.21.0.0/24
