version: '3'
services:
  permissions-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    env_file:
      - .env
    links:
      - mongo
  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - 27017:27017
