#!/bin/bash
echo """
DOCKER_PASS=\"$DOCKER_PASS\"

DOCKER_USER=\"$DOCKER_USER\"

KEYCLOAK_ADMINCLI_SECRET=\"$KEYCLOAK_ADMINCLI_SECRET\"

KEYCLOAK_PERMISSIONS_CLIENT_SECRET=\"$KEYCLOAK_PERMISSIONS_CLIENT_SECRET\"

MONGO_AUTH=\"$MONGO_AUTH\"

MONGO_DB=\"$MONGO_DB\"

MONGO_HOST_TEST=\"$MONGO_HOST_TEST\"

MONGO_HOST=\"$MONGO_HOST\"

MONGO_PASS=\"$MONGO_PASS\"

MONGO_USER=\"$MONGO_USER\"

PERMISSIONS_ADMIN_NAME=\"$PERMISSIONS_ADMIN_NAME\"

PERMISSIONS_ADMIN_PASS=\"$PERMISSIONS_ADMIN_PASS\"

PERMISSIONS_USER_NAME=\"$PERMISSIONS_USER_NAME\"

PERMISSIONS_USER_PASS=\"$PERMISSIONS_USER_PASS\"
"""
