#!/bin/bash
echo """
DOCKER_PASS=\"$DOCKER_PASS\"

DOCKER_USER=\"$DOCKER_USER\"

KEYCLOAK_ADMINCLI_SECRET=\"$KEYCLOAK_ADMINCLI_SECRET\"

KEYCLOAK_PERMISSIONS_CLIENT_SECRET=\"$KEYCLOAK_PERMISSIONS_CLIENT_SECRET\"

MONGO_AUTH=\"$MONGO_AUTH\"

MONGO_DB=\"$MONGO_DB\"

MONGO_HOST_TEST=\"$MONGO_HOST_TEST\"

MONGO_HOST=\"$MONGO_HOST\"

MONGO_PASS=\"$MONGO_PASS\"

MONGO_USER=\"$MONGO_USER\"

DAC_ADMIN_NAME=\"$DAC_ADMIN_NAME\"

DAC_ADMIN_PASS=\"$DAC_ADMIN_PASS\"

DAC_MEMBER_NAME=\"$DAC_MEMBER_NAME\"

DAC_MEMBER_PASS=\"$DAC_MEMBER_PASS\"

REGULAR_USER_NAME=\"$REGULAR_USER_NAME\"

REGULAR_USER_PASS=\"$REGULAR_USER_PASS\"
"""
